---
- hosts: CSR1
  gather_facts: yes
  connection: local
  tasks:
  - name: show run
    ios_command:
      commands:
        - show run
      host: "{{ ansible_host }}"
      username: cisco
      password: cisco
    register: config
  - name: save output to /home/justincase/IT385/ansible/playbooks/backups
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "/home/justincase/IT385/ansible/playbooks/backups/show_run_{{ inventory_hostname }}.txt" 

