---
- hosts: CSR1
  gather_facts: false
  connection: local
  tasks:
  - name: show run
    ios_command:
      commands:
      - sh run
    register: shrun
  - name: report information
    debug:
      var: shrun
