---
- hosts: CSR1
  connection: local
  tasks:
  - name: configure router
    ios_command: 
      commands:
      - conf t
      - hostname CSR1 
      - username ADMIN privilege 15 secret CISCOROCKS
      - no ip domain-lookup
      - banner motd & Warning Any unauthorized access to this device is prohibited &
      - security passwords min-length 10 
      - service password-encryption
      - enable secret class
      - crypto key generate rsa modulus 1024
      - ip ssh version 2
      - ip ssh authentication-retries 3
      - ip ssh time-out 90
      - no ip finger
      - no ip bootp server
      - ip dhcp bootp ignore
      - no service dhcp
      - no mop enabled
      - no ip domain-lookup
      - no service pad
      - no ip http server
      - no ip http secure-server
      - no service config
      - no cdp run
      - no lldp run
      - service tcp-keepalives-in
      - service tcp-keepalives-out
      - line vty 
      - exec-timeout 5
      - line console
      - exec-time-out 5
      - router ospf 1
      - network 192.168.0.11 255.255.255.0 area 1
  - name: configure int g2
    ios_command: 
      commands:
      - conf t
      - int g2
      - ip addr 192.168.51.1 255.255.255.0
      - desc CSR1eth2
      - no shut
  - name: configure int g3
    ios_command: 
      commands:
      - conf t
      - int g3
      - ip addr 192.168.52.1 255.255.255.0
      - desc CSR1eth3
      - no shut
  - name: configure line console
    ios_command:
      commands:
      - line vty
      - exec-timeout 
  - name: configure vty lines 
    ios_command:
      commands:
      - line console
      - exec-timeout 5
  - name: save config
    ios_command:
      commands:
      - wr
- hosts: CSR2
  connection: local
  tasks:  
  - name: configure router
    ios_command: 
      commands:
      - conf t
      - hostname CSR2 
      - username ADMIN privilege 15 secret CISCOROCKS
      - no ip domain-lookup
      - banner motd & Warning Any unauthorized access to this device is prohibited &
      - security passwords min-length 10 
      - service password-encryption
      - enable secret class
      - crypto key generate rsa modulus 1024
      - ip ssh version 2
      - ip ssh authentication-retries 3
      - ip ssh time-out 90
      - no ip finger
      - no ip bootp server
      - ip dhcp bootp ignore
      - no service dhcp
      - no mop enabled
      - no ip domain-lookup
      - no service pad
      - no ip http server
      - no ip http secure-server
      - no service config
      - no cdp run
      - no lldp run
      - service tcp-keepalives-in
      - service tcp-keepalives-out
      - line vty 
      - exec-timeout 5
      - line console
      - exec-time-out 5
      - router ospf 1
      - network 192.168.0.12 255.255.255.0 area 1
  - name: configure int g2
    ios_command: 
      commands:
      - conf t
      - int g2
      - ip addr 192.168.101.1 255.255.255.0
      - desc CSR2eth2
      - no shut
  - name: configure int g3
    ios_command: 
      commands:
      - conf t
      - int g3
      - ip addr 192.168.102.1 255.255.255.0
      - desc CSR2eth3
      - no shut
  - name: configure line console
    ios_command:
      commands:
      - line vty
      - exec-timeout 5
  - name: configure vty lines 
    ios_command:
      commands:
      - line console
      - exec-timeout 5 
  - name: save config
    ios_command:
      commands:
      - wr
