# installLAMP.yml

---
- hosts: linux
  tasks:
  - name: Create user (mshannon/SuperStar!)
    become: yes   # looks better here
    tags: setup
    user: 
      name: mshannon
      password: "{{ 'SuperStar!' | password_hash('sha512') }}"
- hosts: web
  tasks: 
  - name: Install Apache
    become: yes
    tags: setup
    apt: name=apache2 state=present
  - name: Set apache to run
    become: yes
    tags: setup
    service: name=apache2 state=started enabled=yes
  - name: Configure firewall to open http
    become: yes
    tags: setup
    ufw:
      rule: allow
      port: '80'
      proto: tcp 
    notify:
      - restart-firewall
  handlers:
  - name: restart-firewall
    become: yes
    ufw:
      state: reloaded
      
# ansible-playbook -i inventory.txt playbooks/installLampWeb.yml --tags setup 