---
- hosts: linux
  tasks:
  - name: Delete user (egoad/RubberDuck!)
    become: yes	
    tags: setup    
    user:
      name: egoad
      state: absent 
  - name: Delete second user (ddevito/GetShorty!)
    become: yes   # looks better here
    tags: remove
    user: 
      name: ddevito
      state: absent
  - name: Delete another user (webAdmin/encrypted password) 
    become: yes
    tags: remove
    user: 
      name: webAdmin
# go back to ansible and create the password
      state: absent
- hosts: db
  tasks:
  - name: Remove MariaDB
    become: yes
    tags: remove
    apt:
      name: mariadb-server
      state: absent  
- hosts: web
  tasks: 
  - name: Remove Apache
    become: yes
    tags: remove
    apt: name=apache2 state=absent
  - name: Deny firewall to open http
    become: yes
    tags: remove
    ufw:
      rule: deny
      port: '80'
      proto: tcp 
    notify:
      - restart-firewall
  handlers:
  - name: restart-firewall
    become: yes
    ufw:
      state: reloaded

# ansible-playbook -i inventory.txt playbooks/removeLAMP.yml --tags remove